/* Auto-generated by genmsg_cpp for file /home/yuki0w0/ORB_SLAM2/Examples/ROS/ORB_SLAM2/msg/MapKeyPoints.msg */
#ifndef ORB_SLAM2_MESSAGE_MAPKEYPOINTS_H
#define ORB_SLAM2_MESSAGE_MAPKEYPOINTS_H
#include <string>
#include <vector>
#include <map>
#include <ostream>
#include "ros/serialization.h"
#include "ros/builtin_message_traits.h"
#include "ros/message_operations.h"
#include "ros/time.h"

#include "ros/macros.h"

#include "ros/assert.h"

#include "std_msgs/Header.h"

namespace ORB_SLAM2
{
template <class ContainerAllocator>
struct MapKeyPoints_ {
  typedef MapKeyPoints_<ContainerAllocator> Type;

  MapKeyPoints_()
  : header()
  , frametime()
  {
  }

  MapKeyPoints_(const ContainerAllocator& _alloc)
  : header(_alloc)
  , frametime()
  {
  }

  typedef  ::std_msgs::Header_<ContainerAllocator>  _header_type;
   ::std_msgs::Header_<ContainerAllocator>  header;

  typedef ros::Time _frametime_type;
  ros::Time frametime;


  typedef boost::shared_ptr< ::ORB_SLAM2::MapKeyPoints_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::ORB_SLAM2::MapKeyPoints_<ContainerAllocator>  const> ConstPtr;
}; // struct MapKeyPoints
typedef  ::ORB_SLAM2::MapKeyPoints_<std::allocator<void> > MapKeyPoints;

typedef boost::shared_ptr< ::ORB_SLAM2::MapKeyPoints> MapKeyPointsPtr;
typedef boost::shared_ptr< ::ORB_SLAM2::MapKeyPoints const> MapKeyPointsConstPtr;


template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const  ::ORB_SLAM2::MapKeyPoints_<ContainerAllocator> & v)
{
  ros::message_operations::Printer< ::ORB_SLAM2::MapKeyPoints_<ContainerAllocator> >::stream(s, "", v);
  return s;}

} // namespace ORB_SLAM2

namespace ros
{
namespace message_traits
{
template<class ContainerAllocator> struct IsMessage< ::ORB_SLAM2::MapKeyPoints_<ContainerAllocator> > : public TrueType {};
template<class ContainerAllocator> struct IsMessage< ::ORB_SLAM2::MapKeyPoints_<ContainerAllocator>  const> : public TrueType {};
template<class ContainerAllocator>
struct MD5Sum< ::ORB_SLAM2::MapKeyPoints_<ContainerAllocator> > {
  static const char* value() 
  {
    return "29470213d0a3a26fcb867a083181d8d0";
  }

  static const char* value(const  ::ORB_SLAM2::MapKeyPoints_<ContainerAllocator> &) { return value(); } 
  static const uint64_t static_value1 = 0x29470213d0a3a26fULL;
  static const uint64_t static_value2 = 0xcb867a083181d8d0ULL;
};

template<class ContainerAllocator>
struct DataType< ::ORB_SLAM2::MapKeyPoints_<ContainerAllocator> > {
  static const char* value() 
  {
    return "ORB_SLAM2/MapKeyPoints";
  }

  static const char* value(const  ::ORB_SLAM2::MapKeyPoints_<ContainerAllocator> &) { return value(); } 
};

template<class ContainerAllocator>
struct Definition< ::ORB_SLAM2::MapKeyPoints_<ContainerAllocator> > {
  static const char* value() 
  {
    return "Header header\n\
time frametime\n\
\n\
\n\
================================================================================\n\
MSG: std_msgs/Header\n\
# Standard metadata for higher-level stamped data types.\n\
# This is generally used to communicate timestamped data \n\
# in a particular coordinate frame.\n\
# \n\
# sequence ID: consecutively increasing ID \n\
uint32 seq\n\
#Two-integer timestamp that is expressed as:\n\
# * stamp.sec: seconds (stamp_secs) since epoch (in Python the variable is called 'secs')\n\
# * stamp.nsec: nanoseconds since stamp_secs (in Python the variable is called 'nsecs')\n\
# time-handling sugar is provided by the client library\n\
time stamp\n\
#Frame this data is associated with\n\
# 0: no frame\n\
# 1: global frame\n\
string frame_id\n\
\n\
";
  }

  static const char* value(const  ::ORB_SLAM2::MapKeyPoints_<ContainerAllocator> &) { return value(); } 
};

template<class ContainerAllocator> struct HasHeader< ::ORB_SLAM2::MapKeyPoints_<ContainerAllocator> > : public TrueType {};
template<class ContainerAllocator> struct HasHeader< const ::ORB_SLAM2::MapKeyPoints_<ContainerAllocator> > : public TrueType {};
} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

template<class ContainerAllocator> struct Serializer< ::ORB_SLAM2::MapKeyPoints_<ContainerAllocator> >
{
  template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
  {
    stream.next(m.header);
    stream.next(m.frametime);
  }

  ROS_DECLARE_ALLINONE_SERIALIZER
}; // struct MapKeyPoints_
} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::ORB_SLAM2::MapKeyPoints_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const  ::ORB_SLAM2::MapKeyPoints_<ContainerAllocator> & v) 
  {
    s << indent << "header: ";
s << std::endl;
    Printer< ::std_msgs::Header_<ContainerAllocator> >::stream(s, indent + "  ", v.header);
    s << indent << "frametime: ";
    Printer<ros::Time>::stream(s, indent + "  ", v.frametime);
  }
};


} // namespace message_operations
} // namespace ros

#endif // ORB_SLAM2_MESSAGE_MAPKEYPOINTS_H

