// Generated by gencpp from file orb_slam2/MapKeyPoints.msg
// DO NOT EDIT!


#ifndef ORB_SLAM2_MESSAGE_MAPKEYPOINTS_H
#define ORB_SLAM2_MESSAGE_MAPKEYPOINTS_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <std_msgs/Header.h>
#include <geometry_msgs/Point.h>
#include <geometry_msgs/Point.h>

namespace orb_slam2
{
template <class ContainerAllocator>
struct MapKeyPoints_
{
  typedef MapKeyPoints_<ContainerAllocator> Type;

  MapKeyPoints_()
    : header()
    , frametime()
    , mappoints()
    , keypoints()  {
    }
  MapKeyPoints_(const ContainerAllocator& _alloc)
    : header(_alloc)
    , frametime()
    , mappoints(_alloc)
    , keypoints(_alloc)  {
  (void)_alloc;
    }



   typedef  ::std_msgs::Header_<ContainerAllocator>  _header_type;
  _header_type header;

   typedef ros::Time _frametime_type;
  _frametime_type frametime;

   typedef std::vector< ::geometry_msgs::Point_<ContainerAllocator> , typename ContainerAllocator::template rebind< ::geometry_msgs::Point_<ContainerAllocator> >::other >  _mappoints_type;
  _mappoints_type mappoints;

   typedef std::vector< ::geometry_msgs::Point_<ContainerAllocator> , typename ContainerAllocator::template rebind< ::geometry_msgs::Point_<ContainerAllocator> >::other >  _keypoints_type;
  _keypoints_type keypoints;




  typedef boost::shared_ptr< ::orb_slam2::MapKeyPoints_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::orb_slam2::MapKeyPoints_<ContainerAllocator> const> ConstPtr;

}; // struct MapKeyPoints_

typedef ::orb_slam2::MapKeyPoints_<std::allocator<void> > MapKeyPoints;

typedef boost::shared_ptr< ::orb_slam2::MapKeyPoints > MapKeyPointsPtr;
typedef boost::shared_ptr< ::orb_slam2::MapKeyPoints const> MapKeyPointsConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::orb_slam2::MapKeyPoints_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::orb_slam2::MapKeyPoints_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace orb_slam2

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': False, 'IsMessage': True, 'HasHeader': True}
// {'std_msgs': ['/opt/ros/kinetic/share/std_msgs/cmake/../msg'], 'orb_slam2': ['/home/yuki0w0/ORB_SLAM2/Examples/ROS/src/orb_slam2/msg'], 'geometry_msgs': ['/opt/ros/kinetic/share/geometry_msgs/cmake/../msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::orb_slam2::MapKeyPoints_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::orb_slam2::MapKeyPoints_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::orb_slam2::MapKeyPoints_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::orb_slam2::MapKeyPoints_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::orb_slam2::MapKeyPoints_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::orb_slam2::MapKeyPoints_<ContainerAllocator> const>
  : TrueType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::orb_slam2::MapKeyPoints_<ContainerAllocator> >
{
  static const char* value()
  {
    return "b41fe03c1397cf4c381f01fea192e4c6";
  }

  static const char* value(const ::orb_slam2::MapKeyPoints_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xb41fe03c1397cf4cULL;
  static const uint64_t static_value2 = 0x381f01fea192e4c6ULL;
};

template<class ContainerAllocator>
struct DataType< ::orb_slam2::MapKeyPoints_<ContainerAllocator> >
{
  static const char* value()
  {
    return "orb_slam2/MapKeyPoints";
  }

  static const char* value(const ::orb_slam2::MapKeyPoints_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::orb_slam2::MapKeyPoints_<ContainerAllocator> >
{
  static const char* value()
  {
    return "Header header\n\
time frametime\n\
geometry_msgs/Point[] mappoints\n\
geometry_msgs/Point[] keypoints\n\
================================================================================\n\
MSG: std_msgs/Header\n\
# Standard metadata for higher-level stamped data types.\n\
# This is generally used to communicate timestamped data \n\
# in a particular coordinate frame.\n\
# \n\
# sequence ID: consecutively increasing ID \n\
uint32 seq\n\
#Two-integer timestamp that is expressed as:\n\
# * stamp.sec: seconds (stamp_secs) since epoch (in Python the variable is called 'secs')\n\
# * stamp.nsec: nanoseconds since stamp_secs (in Python the variable is called 'nsecs')\n\
# time-handling sugar is provided by the client library\n\
time stamp\n\
#Frame this data is associated with\n\
# 0: no frame\n\
# 1: global frame\n\
string frame_id\n\
\n\
================================================================================\n\
MSG: geometry_msgs/Point\n\
# This contains the position of a point in free space\n\
float64 x\n\
float64 y\n\
float64 z\n\
";
  }

  static const char* value(const ::orb_slam2::MapKeyPoints_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::orb_slam2::MapKeyPoints_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.header);
      stream.next(m.frametime);
      stream.next(m.mappoints);
      stream.next(m.keypoints);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct MapKeyPoints_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::orb_slam2::MapKeyPoints_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::orb_slam2::MapKeyPoints_<ContainerAllocator>& v)
  {
    s << indent << "header: ";
    s << std::endl;
    Printer< ::std_msgs::Header_<ContainerAllocator> >::stream(s, indent + "  ", v.header);
    s << indent << "frametime: ";
    Printer<ros::Time>::stream(s, indent + "  ", v.frametime);
    s << indent << "mappoints[]" << std::endl;
    for (size_t i = 0; i < v.mappoints.size(); ++i)
    {
      s << indent << "  mappoints[" << i << "]: ";
      s << std::endl;
      s << indent;
      Printer< ::geometry_msgs::Point_<ContainerAllocator> >::stream(s, indent + "    ", v.mappoints[i]);
    }
    s << indent << "keypoints[]" << std::endl;
    for (size_t i = 0; i < v.keypoints.size(); ++i)
    {
      s << indent << "  keypoints[" << i << "]: ";
      s << std::endl;
      s << indent;
      Printer< ::geometry_msgs::Point_<ContainerAllocator> >::stream(s, indent + "    ", v.keypoints[i]);
    }
  }
};

} // namespace message_operations
} // namespace ros

#endif // ORB_SLAM2_MESSAGE_MAPKEYPOINTS_H
